PUT  http://localhost:7318/Custom/Cleaning/Masters/V1/Customers/1
Content-Type: application/json

{"CustomerName":"Ritu","Mobile":9322351900,"GSTNumber":"","City":"","Occupation":"","CompanyName":"","BranchName":""}